missionpinball/mpf

.gitignore
machine_files/demo_man/audits/audits.yaml
mpf/devices/playfield.py
mpf/game/game.py
version.py

Bug fix: Crash when no player_controlled_eject_tag was specified

---

mpf/devices/driver.py
version.py

Bug Fix: holdPatter config changed to holdpatter

---

mpf/devices/ball_lock.py
mpf/devices/multiball.py
mpf/mpfconfig.yaml

First version of BallLock and Multiball

---

mpf/devices/score_reel.py
mpf/mpfconfig.yaml

Finished updating code for score reels.

updated score reel and config code for MPF 0.20

---

mpf/system/bcp.py

Modified BCP send_hello function: added 'controller_name' and 'controller_version' parameters to the 'hello' BCP command as discussed in the BCP forum (I know you could have done this in 30 seconds, but I wanted to give the Git tools a try on something trivial)

bcp-hello-enhancement

---

mpf/devices/ball_device.py
mpf/system/ball_controller.py

I need this to account which player lost the ball

pass which device drained the ball

---

mpf/devices/ball_device.py
tests/MpfTestCase.py
tests/machine_files/ball_device/config/test_ball_device.yaml
tests/test_BallDevice.py
tests/test_BallDeviceHoldCoil.py

Just tests. Three out of four currently fail because of the count_balls() problems.

Balldevice problems

---

mpf/system/bcp.py

Added get_led_coordinates function and wired it up as a bcp_get_led_coordinates event handler.

Added get_led_coordinates

---

mpf/devices/servo.py
mpf/devices/servo_controller.py
mpf/mpfconfig.yaml
mpf/platform/p3_roc.py

currently P3-ROC and PCA9685 via I2C only

Add servo p3 roc

---

mpf/core/clock.py
tests/test_EventManager.py

Delay manager race

---

mpf/mpfconfig.yaml
mpf/platform/opp.py

Currently only works for Gen2 hardware.

Add OPP platform interface.

---

mpf/assets/show.py
mpf/config_players/led_player.py
mpf/core/assets.py
mpf/core/clock.py
mpf/core/config_validator.py
mpf/core/rgb_color.py
mpf/core/show_controller.py
mpf/devices/led.py
mpf/devices/matrix_light.py
mpf/tests/machine_files/led/config/led.yaml
mpf/tests/machine_files/led_player/config/led_player.yaml
mpf/tests/machine_files/led_player/modes/mode1/config/mode1.yaml
mpf/tests/test_DeviceLED.py
mpf/tests/test_LedPlayer.py
mpf/tests/test_ShowController.py

Now led_player and shows fully restore lower priority led states when they stop or when a mode ends.

Implemented LED stacks and removed cache, updated tests

---

mpf/core/ball_controller.py
mpf/core/config_validator.py
mpf/core/switch_controller.py
mpf/devices/ball_device.py
mpf/devices/driver.py
mpf/platforms/fast.py
mpf/tests/machine_files/ball_device/config/test_gottlieb_trough.yaml
mpf/tests/machine_files/fast/config/config.yaml
mpf/tests/test_BallController.py
mpf/tests/test_Fast.py
mpf/tests/test_GottliebTrough.py

Support a) from https://missionpinball.com/forum/topic/gottlieb-trough-configuration/#post-8508

Support gottlieb trough

---

mpf/core/scoring.py

validate score entries and bail out early

---

mpf/core/ball_controller.py
mpf/devices/playfield.py
mpf/tests/test_BallController.py

and fix a bug in BallController

Cleanup playfield

---

mpf/devices/diverter.py

remove defunc code in diverter

---

mpf/core/config_validator.py
mpf/core/platform.py
mpf/devices/driver.py
mpf/devices/switch.py
mpf/mpfconfig.yaml
mpf/platforms/fast.py
mpf/platforms/p_roc_common.py
mpf/platforms/virtual.py
mpf/tests/machine_files/platform/config/test_virtual.yaml
mpf/tests/test_Virtual.py

Virtual platform with platform specific variables

---

mpf/platforms/p_roc_common.py
mpf/tests/machine_files/p3_roc/config/config.yaml
mpf/tests/test_P3_Roc.py

Fix led polarity

---

mpf/core/rgb_color.py
mpf/devices/led.py
mpf/mpfconfig.yaml
mpf/tests/machine_files/shots/modes/mode_shot_groups/config/mode_shot_groups.yaml
mpf/tests/test_RGBColor.py

Error handling in rgbcolor

---

mpf/core/config_validator.py

Added action parameter to sound_player in config_validator.

Added action parameter to sound player validation

---

mpf/core/config_validator.py
mpf/core/platform.py
mpf/platforms/opp.py
mpf/tests/machine_files/opp/config/config.yaml
mpf/tests/test_OPP.py

Tested OPP and added the same safeguard as in other platforms (allow_enable). Fixes #172

Port opp to python3

---

mpf/core/ball_controller.py
mpf/devices/ball_device.py
mpf/devices/playfield.py
mpf/tests/test_BallDevice_SmartVirtual.py

Fixes a crash on collect balls

Fix eject and eject all routing

---

mpf/core/config_validator.py
mpf/platforms/opp.py
mpf/tests/machine_files/opp/config/config.yaml
mpf/tests/test_OPP.py

Opp enhancements

---

mpf/core/config_validator.py
mpf/core/mode_device.py
mpf/devices/multiball.py
mpf/tests/machine_files/multiball/modes/mode2/config/mode2.yaml

fixes the multiball part of #225

Fix multiball enable in mode

---

mpf/core/config_validator.py
mpf/tests/machine_files/mode_tests/modes/mode_with_timers/config/mode_with_timers.yaml
mpf/tests/test_Config.py
mpf/tests/test_OPP.py

allow to check the ranges for ints

Improve config validation

---

mpf/platforms/fadecandy.py
mpf/platforms/openpixel.py
mpf/tests/test_Fadecandy.py
mpf/tests/test_Openpixel.py

Python3 strings openpixel

---

mpf/platforms/opp.py
mpf/tests/test_OPP.py

- python2/python3 strings.
- also fix a off by one error in version response parsing

Fix opp strings python3

---

mpf/core/machine.py

Fixes mpf-mc issue https://github.com/missionpinball/mpf-mc/issues/36. Please test on windows

Use temp directory

---

mpf/tests/machine_files/ball_save/config/config.yaml
mpf/tests/machine_files/ball_save/modes/mode1/config/mode1.yaml
mpf/tests/test_BallSave.py

test ball_save in mode

---

mpf/platforms/fast.py
mpf/tests/machine_files/fast/config/config.yaml
mpf/tests/test_FastSerial.py

- test SerialCommunicator
- fix a GI bug

Test fast serial communicator

---

mpf/core/config_validator.py
mpf/tests/machine_files/mode_tests/modes/mode_with_timers/config/mode_with_timers.yaml
mpf/tests/test_ModeTimer.py

Add tests. Fixes #265 
Fix validation of subtract

Test mode timers

---

mpf/core/config_player.py

show a nicer error

---

mpf/devices/matrix_light.py
mpf/tests/machine_files/shows/config/test_shows.yaml
mpf/tests/test_DeviceMatrixLight.py

Test matrix light fade ms

---

machine_files/carousel_example/config/config.yaml
machine_files/carousel_example/config/fast.yaml
machine_files/carousel_example/config/hardware.yaml
machine_files/carousel_example/config/keyboard.yaml
machine_files/carousel_example/config/p_roc.yaml
machine_files/carousel_example/config/test.yaml
machine_files/carousel_example/config/window.yaml
machine_files/carousel_example/modes/attract/config/attract.yaml
machine_files/carousel_example/modes/attract/shows/attract_dmd_loop.yaml
machine_files/carousel_example/modes/base/config/base.yaml
machine_files/carousel_example/modes/bonus/code/bonus.py
machine_files/carousel_example/modes/bonus/config/bonus.yaml
machine_files/carousel_example/modes/carousel/config/carousel.yaml
machine_files/carousel_example/modes/mode_1/config/mode_1.yaml
machine_files/carousel_example/modes/mode_2/config/mode_2.yaml
machine_files/carousel_example/modes/wizard_mode/config/wizard_mode.yaml
mpf/modes/carousel/code/carousel.py

Run the test with:
$ python mc.py carousel_example -x
$ python mpf.py carousel_example -x -c test

Added a carousel mode with a simple example machine and very basic test.

---

mpf/assets/show.py
mpf/core/assets.py
mpf/core/ball_controller.py
mpf/core/ball_search.py
mpf/core/bcp.py
mpf/core/config_player.py
mpf/core/config_processor.py
mpf/core/device_manager.py
mpf/core/machine.py
mpf/core/mode.py
mpf/core/mode_controller.py
mpf/core/platform.py
mpf/devices/score_reel.py
mpf/devices/score_reel_group.py
mpf/migrator/config_version_4.py
mpf/modes/attract/code/attract.py
mpf/modes/credits/code/credits.py
mpf/modes/game/code/game.py
mpf/modes/high_score/code/high_score.py
mpf/modes/tilt/code/tilt.py
mpf/platforms/fast/fast.py
mpf/platforms/opp/opp.py
mpf/platforms/p_roc_common.py
mpf/platforms/smartmatrix.py
mpf/platforms/snux.py
mpf/tests/MpfTestCase.py

Removed a lot of dead code and variables. Both MPF and MPF-MC tests work. Please review if you want to keep anything.

Delete dead code

---

mpf/core/config_validator.py
mpf/core/device.py
mpf/core/machine.py
mpf/core/platform.py
mpf/devices/servo.py
mpf/platforms/fadecandy.py
mpf/platforms/fast/fast.py
mpf/platforms/fast/fast_switch.py
mpf/platforms/i2c_servo_controller.py
mpf/platforms/interfaces/servo_platform_interface.py
mpf/platforms/interfaces/switch_platform_interface.py
mpf/platforms/new_platform_template.py
mpf/platforms/openpixel.py
mpf/platforms/opp/opp.py
mpf/platforms/opp/opp_coil.py
mpf/platforms/opp/opp_incand.py
mpf/platforms/opp/opp_neopixel.py
mpf/platforms/opp/opp_switch.py
mpf/platforms/p3_roc.py
mpf/platforms/p_roc.py
mpf/platforms/p_roc_common.py
mpf/platforms/pololu_maestro.py
mpf/platforms/smartmatrix.py
mpf/platforms/snux.py
mpf/platforms/virtual.py
mpf/tests/test_DeviceMatrixLight.py
mpf/tests/test_Fast.py
mpf/tests/test_OPP.py
mpf/tests/test_Servo.py

Platform cleanup

---

mpf/core/config_validator.py
mpf/devices/motor.py
mpf/mpfconfig.yaml
mpf/tests/machine_files/motor/config/config.yaml
mpf/tests/test_Motors.py

Create a Motor device based on @epotech's scriptlet in  https://missionpinball.com/forum/topic/management-of-motorised-target/#post-8828

Add motor device

---

mpf/commands/both.py

call scripts by executing the commands

---

mpf/devices/ball_device.py
mpf/tests/test_BallDeviceTriggerEvents.py

Fix trigger events on multiball

---

mpf/core/config_validator.py
mpf/core/machine.py
mpf/core/platform.py
mpf/devices/accelerometer.py
mpf/platforms/fadecandy.py
mpf/platforms/fast/fast.py
mpf/platforms/openpixel.py
mpf/platforms/p3_roc.py
mpf/platforms/p_roc.py
mpf/platforms/p_roc_common.py
mpf/platforms/p_roc_devices.py
mpf/platforms/virtual.py
mpf/tests/MpfTestCase.py
mpf/tests/machine_files/p_roc/config/config.yaml
mpf/tests/test_FastSerial.py
mpf/tests/test_P_Roc.py

Add debug to platform

---

mpf/tests/machine_files/credits/config/config_freeplay.yaml
mpf/tests/test_CreditsMode.py

to prevent problems such as:
https://missionpinball.com/forum/topic/0-30-from-0-21-migrator-error/#post-8897

add some more credits mode tests

---

mpf/core/config_validator.py
mpf/core/logic_blocks.py
mpf/tests/machine_files/logic_blocks/config/config.yaml
mpf/tests/machine_files/logic_blocks/modes/mode1/config/mode1.yaml
mpf/tests/test_LogicBlocks.py

Add events when hit

---

mpf/core/machine.py
mpf/modes/bonus/code/bonus.py
mpf/modes/game/code/game.py
mpf/modes/tilt/code/tilt.py
mpf/tests/test_Bonus.py

Bring back tilted attribtue
